### ISSUE TITLE
Modify naming and attributes of time variables on history files to be consistent with other CESM components

### ISSUE THREAD

**Issue by phillips-ad** [ESCOMP/WW3-CESM#22]
These changes are being requested to improve the ease-of-access of CESM data and to normalize the look of the metadata across CESM components. See https://github.com/ESCOMP/CESM/issues/194 and especially the google doc referenced from https://github.com/ESCOMP/CESM/issues/194#issuecomment-961443965.

Current time array output:

	double time(time) ;
		time:units = "seconds since YYYY-MM-DD HH:MM:SS" ;
		time:calendar = "noleap" ;

Proposed time array output:

	double time(time) ;
		time:long_name = "time" ;
		time:units = "days since YYYY-MM-DD HH:MM:SS" ;
		time:bounds = "time_bounds" ;
		time:calendar = "noleap" ;
	double time_bounds(time, nbnd) ;
		time_bounds:long_name = "time interval endpoints" ;
		time_bounds:units = "days since YYYY-MM-DD HH:MM:SS" ;
		time_bounds:calendar = "noleap" ;

Changes made: change units of time to “days since”, add long_name and bounds attributes, add time_bounds array and long_name, units and calendar attributes

There is a difference in the time@units values between MOM6 (days since 0001-01-01 00:00:00) and WW3 (seconds since the start of the run). I do not know if this is a big deal or not. Regardless, the matching request for MOM6 can be found at https://github.com/ESCOMP/MOM_interface/issues/107.

@billsacks @phillips-ad @strandwg are filing similar issues for each component.

**Comment by billsacks** [comment]
Based on discussion with @klindsay28 and @phillips-ad this isn't feasible for CESM3 and isn't critical, so we're closing it as a wontfix.
