### ISSUE TITLE
Set time value for averaged quantities to midpoint of averaging period

### ISSUE THREAD

**Issue by phillips-ad** [ESCOMP/WW3-CESM#23]
This is linked to https://github.com/ESCOMP/CAM/issues/159 and https://github.com/ESCOMP/CTSM/issues/1059, and involves setting the WW3 output time value to the center of the averaging period. Different components may end up handling output differently, but the going consensus so far is to separate instantaneous data streams from averaged/min/max data streams. This might be what is happening with present output, but as the output does not contain a time_bounds array (see https://github.com/ESCOMP/WW3-CESM/issues/22) I cannot check this.

**Comment by billsacks** [comment]
Based on discussion with @klindsay28 and @phillips-ad this isn't feasible for CESM3 and isn't critical, so we're closing it as a wontfix.
